
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itrjjjrwthdhmeysgjlm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0cmpqanJ3dGhkaG1leXNnamxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MDY3MjYsImV4cCI6MjA2MTE4MjcyNn0.vwTYvDOllmfoBmow8-2ltytkd0vipMIJtsPqABC7Xfo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
