
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://itrjjjrwthdhmeysgjlm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0cmpqanJ3dGhkaG1leXNnamxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MDY3MjYsImV4cCI6MjA2MTE4MjcyNn0.vwTYvDOllmfoBmow8-2ltytkd0vipMIJtsPqABC7Xfo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Initialize the Supabase client with better persistence configuration
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false,
    storage: typeof window !== 'undefined' ? localStorage : undefined
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  }
});

// Set up the Supabase realtime client
supabase.realtime.setAuth(SUPABASE_PUBLISHABLE_KEY);
